<ns0:test-suite xmlns:ns0="urn:model.allure.qatools.yandex.ru" start="1554608936799" stop="1554608937728">
  <name>testcase</name>
  <labels/>
  <test-cases>
    <test-case start="1554608936799" status="passed" stop="1554608936970">
      <name>C:\Users\Administrator\PycharmProjects\pytest\testcase\sys.test_sys_changePwd.Test_changePwd.test_changePwd</name>
      <attachments/>
      <labels>
        <label name="feature" value="修改密码模块"/>
        <label name="story" value="修改密码1*******************"/>
        <label name="severity" value="normal"/>
        <label name="thread" value="368-MainThread"/>
        <label name="host" value="SKY-20180902WUV"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1554608936971" status="passed" stop="1554608937139">
      <name>C:\Users\Administrator\PycharmProjects\pytest\testcase\sys.test_sys_changePwd.Test_changePwd.test_changePwd1</name>
      <attachments/>
      <labels>
        <label name="feature" value="修改密码模块"/>
        <label name="story" value="修改密码2*******************"/>
        <label name="severity" value="normal"/>
        <label name="thread" value="368-MainThread"/>
        <label name="host" value="SKY-20180902WUV"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1554608937140" status="passed" stop="1554608937220">
      <name>C:\Users\Administrator\PycharmProjects\pytest\testcase\sys.test_sys_getUserInfo.Test_getUserInfo.test_getUserInfo</name>
      <attachments/>
      <labels>
        <label name="feature" value="获取用户信息模块"/>
        <label name="story" value="正确获取用户信息"/>
        <label name="severity" value="normal"/>
        <label name="thread" value="368-MainThread"/>
        <label name="host" value="SKY-20180902WUV"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1554608937221" status="passed" stop="1554608937266">
      <name>C:\Users\Administrator\PycharmProjects\pytest\testcase\sys.test_sys_login.Test_Login.test_login</name>
      <attachments/>
      <labels>
        <label name="feature" value="登录模块"/>
        <label name="story" value="正确登录"/>
        <label name="severity" value="normal"/>
        <label name="thread" value="368-MainThread"/>
        <label name="host" value="SKY-20180902WUV"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1554608937269" status="failed" stop="1554608937372">
      <name>C:\Users\Administrator\PycharmProjects\pytest\testcase\sys.test_sys_login.Test_Login.test_login_fail</name>
      <failure>
        <message>AssertionError: assert 301 == 410</message>
        <stack-trace>self = &lt;testcase.sys.test_sys_login.Test_Login object at 0x000001DF5E0D6240&gt;

    @allure.story('用户名不正确')
    def test_login_fail(self):
        data = {
            'userName':'123456789',
            'password':'123456'
        }
        resp = http.post('/sys/login',data)
&gt;       assert resp['code'] == 410
E       assert 301 == 410

testcase\sys\test_sys_login.py:26: AssertionError</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="feature" value="登录模块"/>
        <label name="story" value="用户名不正确"/>
        <label name="severity" value="normal"/>
        <label name="thread" value="368-MainThread"/>
        <label name="host" value="SKY-20180902WUV"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1554608937374" status="failed" stop="1554608937433">
      <name>C:\Users\Administrator\PycharmProjects\pytest\testcase\sys.test_sys_login.Test_Login.test_login_fail1</name>
      <failure>
        <message>AssertionError: assert 301 == 410</message>
        <stack-trace>self = &lt;testcase.sys.test_sys_login.Test_Login object at 0x000001DF5E0F1EB8&gt;

    @allure.story('用户名太长')
    def test_login_fail1(self):
        data = {
            'userName': '1222131564789465451234889546546136548894165',
            'password': '123456'
        }
        resp = http.post('/sys/login', data)
&gt;       assert resp['code'] == 410
E       assert 301 == 410

testcase\sys\test_sys_login.py:37: AssertionError</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="feature" value="登录模块"/>
        <label name="story" value="用户名太长"/>
        <label name="severity" value="normal"/>
        <label name="thread" value="368-MainThread"/>
        <label name="host" value="SKY-20180902WUV"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1554608937434" status="passed" stop="1554608937463">
      <name>C:\Users\Administrator\PycharmProjects\pytest\testcase\sys.test_sys_login.Test_Login.test_login_fail2</name>
      <attachments/>
      <labels>
        <label name="feature" value="登录模块"/>
        <label name="story" value="密码不正确"/>
        <label name="severity" value="normal"/>
        <label name="thread" value="368-MainThread"/>
        <label name="host" value="SKY-20180902WUV"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1554608937464" status="failed" stop="1554608937505">
      <name>C:\Users\Administrator\PycharmProjects\pytest\testcase\sys.test_sys_login.Test_Login.test_login_fail3</name>
      <failure>
        <message>AssertionError: assert 3010 == 410</message>
        <stack-trace>self = &lt;testcase.sys.test_sys_login.Test_Login object at 0x000001DF5E1098D0&gt;

    @allure.story('用户名为空')
    def test_login_fail3(self):
        data = {
            'userName': '',
            'password': '456789'
        }
        resp = http.post('/sys/login', data)
&gt;       assert resp['code'] == 410
E       assert 3010 == 410

testcase\sys\test_sys_login.py:59: AssertionError</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="feature" value="登录模块"/>
        <label name="story" value="用户名为空"/>
        <label name="severity" value="normal"/>
        <label name="thread" value="368-MainThread"/>
        <label name="host" value="SKY-20180902WUV"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1554608937508" status="passed" stop="1554608937576">
      <name>C:\Users\Administrator\PycharmProjects\pytest\testcase\sys.test_sys_login.Test_Login.test_login_fail4</name>
      <attachments/>
      <labels>
        <label name="feature" value="登录模块"/>
        <label name="story" value="密码为空"/>
        <label name="severity" value="normal"/>
        <label name="thread" value="368-MainThread"/>
        <label name="host" value="SKY-20180902WUV"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1554608937577" status="failed" stop="1554608937728">
      <name>C:\Users\Administrator\PycharmProjects\pytest\testcase\user.test_sys_zhuce.Test_Login.test_zhuce</name>
      <failure>
        <message>AssertionError: assert 1284 == 1089</message>
        <stack-trace>self = &lt;testcase.user.test_sys_zhuce.Test_Login object at 0x000001DF5E0FC2B0&gt;

    @allure.story('注销')
    def test_zhuce(self):
        data = {
            "nickName":"wwwuuu",
            "userName":"15922922114",
            "telNo":"",
            "email":"",
            "address":"",
            "roleIds":"",
            "regionId":1,
            "regionLevel":1
        }
        resp = http.post('/user/saveOrUpdateUser', data)
        # assert resp['code'] == 401
        # assert resp['msg'] == "无权限访问"
        print(resp)
        user=data['userName']
        id=self.login1(user)
&gt;       self.huoqu(user,id)

testcase\user\test_sys_zhuce.py:27: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = &lt;testcase.user.test_sys_zhuce.Test_Login object at 0x000001DF5E0FC2B0&gt;
zhuce = '15922922114', id = 1089

    def huoqu(self,zhuce,id):
        data = {"pageCurrent":1,"pageSize":10,"nickName":"","userName":"","regionId":1}
    
        resp = http.post('/user/loadUserList', data)
    
        assert resp['code'] == 200
        assert resp['msg'] == "操作成功"
&gt;       assert resp['object']['list'][0]['id'] == id
E       assert 1284 == 1089

testcase\user\test_sys_zhuce.py:48: AssertionError</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="feature" value="注册模块"/>
        <label name="story" value="注销"/>
        <label name="severity" value="normal"/>
        <label name="thread" value="368-MainThread"/>
        <label name="host" value="SKY-20180902WUV"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
  </test-cases>
</ns0:test-suite>
